"""added followers function to user model

Revision ID: 33016aadbb73
Revises: 5d6afda876cb
Create Date: 2020-12-28 15:35:11.661892

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33016aadbb73'
down_revision = '5d6afda876cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
