"""updated user model

Revision ID: b622edbf41c1
Revises: c0c3cb5ffeff
Create Date: 2021-01-15 11:25:39.321482

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b622edbf41c1'
down_revision = 'c0c3cb5ffeff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_customer', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_customer')
    # ### end Alembic commands ###
